### ISSUE TITLE
Compile the ADSBX feeder client using READSB

### ISSUE THREAD

**Issue by adsbxchange** [mikenye/docker-adsbexchange#1]
Compile the ADSBX feeder using READSB

git clone --depth 1 https://github.com/Mictronics/readsb.git
cd readsb
make RTLSDR=yes

 /usr/bin/readsb --net --net-only --quiet \
   --net-beast-reduce-interval 1 \
   --net-connector feed.adsbexchange.com,30005,beast_reduce_out \
   --net-connector localhost,30005,beast_in \
   --net-ro-interval 0.5 --net-ri-port 0 --net-ro-port 0 \
   --net-sbs-port 0 --net-bi-port 0 --net-bo-port 0

**Comment by adsbxchange** [comment]
https://github.com/adsbxchange/adsb-exchange

I hacked above into out feeder installer.  Hopefully I didn't break anything too badly.

Based on @wiedehopf work here:
https://github.com/wiedehopf/lowBandwidthFeedAdsbX

One of the things to consider adding is this:
https://github.com/adsbxchange/adsbexchange-stats
Step 2 is the setup.

It allows to the individual feeder map and eventually a "stats" dashboard to fulfill the deepest desires of the masses.

The problem is it directly reads the aircraft.json from dump1090 et all forks

JSON_PATHS=( "/run/readsb" "/run/dump1090-mutability" "/run/dump1090-fa" )

https://www.adsbexchange.com/api/feeders/?feed=v9FBlUbrsPtzcExw4o1oHuPamuv8SW452njzmw7ejaVRAYZEFF2jjFTAF35H4eiq&t=

https://www.adsbexchange.com/api/feeders/tar1090/?feed=v9FBlUbrsPtzcExw4o1oHuPamuv8SW452njzmw7ejaVRAYZEFF2jjFTAF35H4eiq&t=

I'm sure it will gain traction and other contributors if you care to join ADSBx discord.

https://discord.gg/DReE2Da

Cheers!

**Comment by mikenye** [comment]
Thanks so much for the suggestions. I've updated the container (version 20200212) implementing both of the above suggestions (`readsb` and `adsbexchange-stats`).

I've also joined the ADSBx discord and look forward to talking with you.
