### ISSUE TITLE
Make MLAT Privacy Configurable

### ISSUE THREAD

**Issue by kyleinprogress** [mikenye/docker-adsbexchange#14]
Would it be possible to make MLAT privacy configurable? Maybe through an environment variable setting?

https://github.com/mikenye/docker-adsbexchange/blob/6203ba54f6ec78d5d118a1a7380b931bc1de0072/etc/services.d/mlat-client/run#L5-L16

**Comment by mikenye** [comment]
Hi @kyleinprogress your changes have been merged into master and the images on docker hub have been updated! Thanks so much!
