### ISSUE TITLE
Non-privileged option?

### ISSUE THREAD

**Issue by courtarro** [mikenye/docker-adsbexchange#34]
I'm interested in using a container like this to feed ADSB Exchange, but it looks like the dependency on s6 prevents running as non-root. Have you put any thought into what it would take to run as a normal user?

**Comment by mikenye** [comment]
Running the adsbx binaries (feeder & mlat-client) as a non-privilaged user would be pretty straightforward and I could implement that fairly quickly (using `s6-setuidgid`).

The latest version of s6-overlay does support using docker's `USER` directive to run the entire container as non-root, however this would require some re-architecture and would likely take a lot longer.

If it's acceptable to you, I can implement `s6-setuidgid` now(ish), and work towards supporting docker's `USER` directive longer term, as s6-overlay's support for this matures.

Let me know what you think.

**Comment by courtarro** [comment]
It's your project, so I don't want to give you demands to meet my needs! But if there's low-hanging fruit, it would be good to do for the project. Do I understand that the container would boot s6 as root, and s6 would then deescalate the privileges of the services? That's probably good for most cases, but the best long-term solution would be one where it doesn't need to run as root.

I've just gotten leery of running DockerHub-sourced images as root since you never know when an image maintainer could be compromised. I get paranoid that a publicly downloaded image might be replaced with something that does bad things if it runs as root, but unfortunately a huge part of the Docker ecosystem expects everyone to work that way.

Thanks!

**Comment by mikenye** [comment]
> It's your project, so I don't want to give you demands to meet my needs!
While it is my project, it is used by many ADSB enthusiasts all over the world, so it would be remiss of me not to secure the container to the best of my abilities. Running the processes as "root" isn't ideal and has been on my todo list for some time. This issue is good motivation to implement better security. :-)

> Do I understand that the container would boot s6 as root, and s6 would then deescalate the privileges of the services?
Yes that's correct. s6-overlay's support for using docker's USER directive is bleeding edge, see https://github.com/just-containers/s6-overlay#user-directive.

> That's probably good for most cases, but the best long-term solution would be one where it doesn't need to run as root.
I totally agree, I'll have to have a play with s6-overlay and docker's USER directive and see what breaks.

> I've just gotten leery of running DockerHub-sourced images as root since you never know when an image maintainer could be compromised. I get paranoid that a publicly downloaded image might be replaced with something that does bad things if it runs as root, but unfortunately a huge part of the Docker ecosystem expects everyone to work that way.
Completely understand.

Expect to see the deescalation of privilages for processes running within the container shortly, and support for USER longer term (or shorter if nothing breaks).

**Comment by mikenye** [comment]
Branch https://github.com/mikenye/docker-adsbexchange/tree/rootless has been created for the modifications associated with this request.

**Comment by mikenye** [comment]
Image `mikenye/adsbexchange:20200917` is the last version of the image prior to moving services to non-root users within the container.

**Comment by courtarro** [comment]
Awesome - thanks a bunch. I will check it out as soon as possible.

**Comment by mikenye** [comment]
No problems. I'm currently testing out completely rootless. Seems ok.

**Comment by mikenye** [comment]
I've been running rootless for the past couple of hours, it seems to work absolutely fine. I will merge the changes into master.

**Comment by mikenye** [comment]
OK. `mikenye/adsbexchange:latest` uses the "USER" directive to run as an unprivilieged user.
