### ISSUE TITLE
health_from_adsbexchange throws KeyError for 'stats-uuid'

### ISSUE THREAD

**Issue by hakan42** [mikenye/docker-adsbexchange#52]
I am running the adsb-exchange container via "docker run", feeding all the environment variables that are referenced in the compose file. Every few minutes, I see following error:

    Apr 18 23:19:23 wallaby run.sh[30718]: [healthcheck]
    Apr 18 23:19:23 wallaby run.sh[30718]: Traceback (most recent call last):
    Apr 18 23:19:23 wallaby run.sh[30718]:   File "/scripts/health_from_adsbexchange.py", line 17, in <module>
    Apr 18 23:19:23 wallaby run.sh[30718]:     if stats_json['stats-uuid'].lower() == 'not found':
    Apr 18 23:19:23 wallaby run.sh[30718]: KeyError: 'stats-uuid'
    Apr 18 23:19:24 wallaby run.sh[30718]: [adsbexchange-feed] Statistics: Sun Apr 18 23:04:23 2021 CEST - Sun Apr 18 23:19:24 2021 CEST

**Comment by hakan42** [comment]
Fetching my json and piping it through jq gives the following, please note that I am seeing "stats-uuid1" and "feed-string1":

    hakan@wallaby:~$ curl --silent https://www.adsbexchange.com/myip/ | jq "."
    {
      "ua": "curl/7.47.0",
      "outlines": "7",
      "stats-uuid1": "my-uuid",
      "feed-string1": "my-feed-string",
      "rt7": "91.16.234.98 beast.front beast.back beast-ingress.03",
      "age7": "19m41s",
      "rt9": "91.16.234.98 beast.front beast.back beast-ingress.03",
      "age9": "19m41s",
      "rt14": "91.16.234.98 mlat.front mlat.back.4b mlat4b",
      "age14": "19m39s"
    }

**Comment by mikenye** [comment]
It looks like the folks at adsbx have changed the JSON format. I'll update the health script.

**Comment by mikenye** [comment]
This should now be fixed. Can you please pull the latest version and let me know how you go.

**Comment by hakan42** [comment]
The KeyError is gone, the container shows "healthy" since about 45 minutes. And I can see nice output of healthcheck in the docker logs,

Should be fixed :)

**Comment by mikenye** [comment]
Awesome, thanks for letting me know. :)
